// <auto-generated />
using System;
using FixItNow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FixItNow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409122219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FixItNow.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FixItNow.Api.Models.RepairRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("bit");

                    b.Property<string>("RejectedWorkerIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetWorkerIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepairRequests");
                });

            modelBuilder.Entity("FixItNow.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FixItNow.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Nguy?n Van A",
                            PasswordHash = "123456",
                            Phone = "0900000001",
                            Role = 1,
                            WorkerProfileId = 101
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Tr?n Th? B",
                            PasswordHash = "123456",
                            Phone = "0900000002",
                            Role = 1,
                            WorkerProfileId = 102
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Ph?m C",
                            PasswordHash = "123456",
                            Phone = "0900000003",
                            Role = 1,
                            WorkerProfileId = 103
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Lê Van D",
                            PasswordHash = "123456",
                            Phone = "0900000004",
                            Role = 1,
                            WorkerProfileId = 104
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Ph?m Van E",
                            PasswordHash = "123456",
                            Phone = "0900000005",
                            Role = 1,
                            WorkerProfileId = 105
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng M?t",
                            PasswordHash = "123456",
                            Phone = "0900000006",
                            Role = 0
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Hai",
                            PasswordHash = "123456",
                            Phone = "0900000007",
                            Role = 0
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Ba",
                            PasswordHash = "123456",
                            Phone = "0900000008",
                            Role = 0
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng B?n",
                            PasswordHash = "123456",
                            Phone = "0900000009",
                            Role = 0
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Nam",
                            PasswordHash = "123456",
                            Phone = "0900000010",
                            Role = 0
                        });
                });

            modelBuilder.Entity("FixItNow.Api.Models.WorkerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOrStore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "123 Lê L?i, Qu?n 1",
                            Description = "S?a di?n nhanh chóng, an toàn",
                            IsActive = true,
                            Location = "H? Chí Minh",
                            NameOrStore = "Th? Ði?n Nguy?n Van A",
                            PhoneNumber = "0900000001",
                            Rating = 4.7999999999999998,
                            Services = "S?a di?n,Máy l?nh"
                        },
                        new
                        {
                            Id = 102,
                            Address = "456 Tr?n Hung Ð?o, Hoàn Ki?m",
                            Description = "Chuyên s?a ?ng nu?c, vòi sen",
                            IsActive = true,
                            Location = "Hà N?i",
                            NameOrStore = "Tr?n Th? B D?ch V? Nu?c",
                            PhoneNumber = "0900000002",
                            Rating = 4.5,
                            Services = "S?a nu?c"
                        },
                        new
                        {
                            Id = 103,
                            Address = "789 Nguy?n Van Linh, H?i Châu",
                            Description = "Thay l?c t? l?nh, ki?m tra tivi",
                            IsActive = true,
                            Location = "Ðà N?ng",
                            NameOrStore = "C?a hàng S?a Ch?a C",
                            PhoneNumber = "0900000003",
                            Rating = 5.0,
                            Services = "Ði?n gia d?ng,Máy l?nh"
                        },
                        new
                        {
                            Id = 104,
                            Address = "101 Lý T? Tr?ng, Ninh Ki?u",
                            Description = "Nh?n s?a m?i th? trong nhà",
                            IsActive = true,
                            Location = "C?n Tho",
                            NameOrStore = "Lê Van D - Ða nang",
                            PhoneNumber = "0900000004",
                            Rating = 4.2000000000000002,
                            Services = "S?a di?n,S?a nu?c,Ði?n gia d?ng"
                        },
                        new
                        {
                            Id = 105,
                            Address = "202 Ð?ng Kh?i, Biên Hòa",
                            Description = "Chuyên s?a c?a g?, t? g?",
                            IsActive = true,
                            Location = "Ð?ng Nai",
                            NameOrStore = "Ph?m Van E M?c",
                            PhoneNumber = "0900000005",
                            Rating = 4.7000000000000002,
                            Services = "Khác"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
